SAMPLE_PATIENTS = [
    {
        "patient_id": "P-1001",
        "name": "Maria Thompson",
        "age": 63,
        "sex": "Female",
        "race": "White",
        "ethnicity": "Non-Hispanic",
        "city": "New York",
        "diagnoses": ["Type 2 diabetes mellitus", "Chronic kidney disease stage 3", "Hypertension"],
        "medications": ["Metformin", "Lisinopril", "Amlodipine"],
        "labs": {"A1c": "8.2%", "eGFR": "48", "Creatinine": "1.5", "Albumin/Creatinine Ratio": "210"},
        "encounters": ["Primary care follow-up", "Nephrology consult"],
        "clinical_summary": "Diabetes with worsening renal function over the past year, persistent albuminuria, and elevated blood pressure despite therapy."
    },
    {
        "patient_id": "P-1002",
        "name": "James Carter",
        "age": 71,
        "sex": "Male",
        "race": "Black",
        "ethnicity": "Non-Hispanic",
        "city": "Newark",
        "diagnoses": ["Congestive heart failure", "Atrial fibrillation", "Recurrent emergency department visits"],
        "medications": ["Furosemide", "Apixaban", "Metoprolol"],
        "labs": {"BNP": "640", "Sodium": "133", "Creatinine": "1.3"},
        "encounters": ["Emergency department visit", "Cardiology follow-up", "Hospital discharge"],
        "clinical_summary": "Older patient with heart failure exacerbations, fluid overload, lower extremity edema, and repeated emergency department utilization over the last six months."
    },
    {
        "patient_id": "P-1003",
        "name": "Elena Ruiz",
        "age": 54,
        "sex": "Female",
        "race": "Other",
        "ethnicity": "Hispanic",
        "city": "Brooklyn",
        "diagnoses": ["Breast cancer", "Immunotherapy treatment", "Cancer-related fatigue"],
        "medications": ["Pembrolizumab", "Ondansetron"],
        "labs": {"Hemoglobin": "10.9", "WBC": "5.2"},
        "encounters": ["Oncology infusion visit", "Breast oncology consult"],
        "clinical_summary": "Patient undergoing immunotherapy for breast malignancy with treatment-related fatigue, intermittent nausea, and oncology follow-up care."
    },
    {
        "patient_id": "P-1004",
        "name": "Robert Lee",
        "age": 46,
        "sex": "Male",
        "race": "Asian",
        "ethnicity": "Non-Hispanic",
        "city": "Jersey City",
        "diagnoses": ["Asthma", "Seasonal allergies", "Intermittent wheezing"],
        "medications": ["Albuterol", "Fluticasone", "Cetirizine"],
        "labs": {},
        "encounters": ["Pulmonology follow-up"],
        "clinical_summary": "Moderate persistent asthma with increased rescue inhaler use during allergy season and occasional nighttime cough."
    },
    {
        "patient_id": "P-1005",
        "name": "Nina Patel",
        "age": 68,
        "sex": "Female",
        "race": "Asian",
        "ethnicity": "Non-Hispanic",
        "city": "Queens",
        "diagnoses": ["Lung cancer", "Smoking history", "Weight loss"],
        "medications": ["Carboplatin", "Paclitaxel"],
        "labs": {"WBC": "3.9", "Platelets": "145"},
        "encounters": ["Thoracic oncology visit", "Infusion center visit"],
        "clinical_summary": "Patient with lung malignancy, prior smoking history, progressive weight loss, and active chemotherapy treatment."
    },
    {
        "patient_id": "P-1006",
        "name": "Olivia Grant",
        "age": 37,
        "sex": "Female",
        "race": "White",
        "ethnicity": "Non-Hispanic",
        "city": "Manhattan",
        "diagnoses": ["Systemic lupus erythematosus", "Joint pain", "Fatigue"],
        "medications": ["Hydroxychloroquine", "Prednisone"],
        "labs": {"ANA": "Positive", "ESR": "42"},
        "encounters": ["Rheumatology visit"],
        "clinical_summary": "Autoimmune disease flare with fatigue, arthralgias, and elevated inflammatory markers prompting rheumatology follow-up."
    },
    {
        "patient_id": "P-1007",
        "name": "Daniel Brooks",
        "age": 59,
        "sex": "Male",
        "race": "White",
        "ethnicity": "Non-Hispanic",
        "city": "Bronx",
        "diagnoses": ["Type 2 diabetes mellitus", "Peripheral neuropathy", "Foot ulcer"],
        "medications": ["Insulin glargine", "Gabapentin", "Losartan"],
        "labs": {"A1c": "9.1%", "Glucose": "214"},
        "encounters": ["Endocrinology consult", "Wound care visit"],
        "clinical_summary": "Long-standing diabetes with poor glycemic control, neuropathic pain, and lower extremity ulcer requiring wound care monitoring."
    },
    {
        "patient_id": "P-1008",
        "name": "Patricia Howard",
        "age": 76,
        "sex": "Female",
        "race": "Black",
        "ethnicity": "Non-Hispanic",
        "city": "Staten Island",
        "diagnoses": ["Chronic obstructive pulmonary disease", "Former smoker", "Shortness of breath"],
        "medications": ["Tiotropium", "Albuterol", "Prednisone"],
        "labs": {"Oxygen saturation": "91%"},
        "encounters": ["Pulmonary clinic visit", "Urgent care visit"],
        "clinical_summary": "Elderly patient with COPD, dyspnea on exertion, recent urgent care evaluation, and inhaler-based maintenance therapy."
    }
]
